#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# enable ctrl
bindkey -e

# tabs -4

# EDITOR=vim
alias v='$EDITOR'
alias zrc='~/.dotfiles/zsh/'
alias zr='$EDITOR ~/.zshrc'
alias vr='$EDITOR ~/.vimrc'
alias lt='ls -lAhtr'
alias lz='ls -lAS'
alias gno='gnome-open'
alias q="exit"
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias doc="cd ~/Documents"
alias ws='cd ~/Workspace'
alias make='nocorrect make' #stop make from autocorrecting things
alias szsh="source ~/.zshrc" # source zsh
alias python=python2.7
alias gaa='git add -A'
alias ga='git add'
alias gs='git status'
alias gd='git diff'
alias pg='ps aux | grep'
alias py=python3
alias ipy=ipython3
# export PYTHONPATH=$PYTHONPATH:/home/jt2/Workspace/python/gdata-python-client/src
#
source /usr/local/bin/virtualenvwrapper.sh

#Hierarchy Viewer Variable (Android Studios)
export ANDROID_HVPROTO=ddm

export NODE_PATH=/usr/local/lib/node_modules/

#executable scripts
export set PATH=$PATH:~/Workspace/scripts

#set font for octave-gui
export FONTCONFIG_PATH=/opt/X11/lib/X11/fontconfig



# tabtab source for yo package
# uninstall by removing these lines or running `tabtab uninstall yo`
[[ -f /usr/local/lib/node_modules/yo/node_modules/tabtab/.completions/yo.zsh ]] && . /usr/local/lib/node_modules/yo/node_modules/tabtab/.completions/yo.zsh
