#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

SH=$(basename $SHELL)

if type nvim >/dev/null 2>&1; then
    export EDITOR='nvim'
    export VISUAL='nvim'
elif type vim >/dev/null 2>&1; then
    export EDITOR='vim'
    export VISUAL='vim'
else
    export EDITOR='vi'
    export VISUAL='vi'
fi

###########
# GENERAL #
###########
alias lt='ls -lAhtr'
alias lz='ls -lAS'
alias q="exit"
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias doc="cd ~/Documents"
alias ws='cd ~/Workspace'
alias make='nocorrect make' #stop make from autocorrecting things
alias szsh="source ~/.zshrc" # source zsh
alias gaa='git add -A'
alias ga='git add'
alias gs='git status'
alias gd='git diff'
alias pg='ps aux | grep'

if [[ $SH == 'zsh' ]]; then
    # Source Prezto.
    if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
        source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
    fi

    # enable ctrl
    bindkey -e

    source /usr/local/bin/virtualenvwrapper.sh
    alias open='gnome-open'
    alias v='$EDITOR'
    alias zrc='~/.dotfiles/zsh/'
    alias zr='$EDITOR ~/.zshrc'
    alias vr='$EDITOR ~/.vimrc'
    alias py=python3
    alias ipy=ipython3
    alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
    alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
    if type colordiff >/dev/null 2>&1; then
        alias diff='colordiff'
    fi

    #Hierarchy Viewer Variable (Android Studios)
    export ANDROID_HVPROTO=ddm

    export NODE_PATH=/usr/local/lib/node_modules/

    #executable scripts
    export set PATH=$PATH:~/Workspace/scripts

    #set font for octave-gui
    export FONTCONFIG_PATH=/opt/X11/lib/X11/fontconfig

    #remove -S flag from zprofile default
    export LESS='-F -g -i -M -R -w -X -z-4'


    # tabtab source for yo package
    # uninstall by removing these lines or running `tabtab uninstall yo`
    [[ -f /usr/local/lib/node_modules/yo/node_modules/tabtab/.completions/yo.zsh ]] && . /usr/local/lib/node_modules/yo/node_modules/tabtab/.completions/yo.zsh
fi
