#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

link_zsh () {
    echo "Linking files"
    for rcfile in $DIR/runcoms/[!README.md]*; do
        ln -sh $rcfile $HOME/.$(basename $rcfile)
    done
}

if type zsh >/dev/null 2>&1; then
    link_zsh
    chsh -s /bin/zsh
else
    echo "No zsh installed!"
    if [ -n "$BASH_VERSION" ]; then
        if [ -f $HOME/.bashrc ]; then
            echo "Backup current .bashrc to .bashrc.backup"
            mv $HOME/.bashrc $HOME/.bashrc.backup
        fi
        echo "Linking to .bashrc"
        ln -sh $DIR/runcoms/zshrc $HOME/.bashrc
    fi
fi
