#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
OS="$(uname -s)"

link_zsh () {
    echo 
    echo "Linking files"
    echo
    for rcfile in $DIR/runcoms/[!README.md]*; do
        ln -s $rcfile $HOME/.$(basename $rcfile)
    done

    echo "$(basename $0)"

    # Don't do anything to profile
    # if [[ $(basename $SHELL) == "bash" ]]; then
        # echo "Curent shell is bash. Appending to zsh to .profile"
        # echo "export SHELL=/bin/zsh" >> ~/.profile
        # echo "exec /bin/zsh -l" >> ~/.profile

        # echo "Please relog now"
    # fi
}

if type zsh >/dev/null 2>&1; then
    link_zsh
else
    echo "No zsh installed!"
    if [ -n "$BASH_VERSION" ]; then
        if [ -f $HOME/.bashrc ]; then
            echo "Backup current .bashrc to .bashrc.backup"
            mv $HOME/.bashrc $HOME/.bashrc.backup
        fi
        echo "Linking to .bashrc"
        ln -sn $DIR/runcoms/zshrc $HOME/.bashrc
        source $HOME/.bashrc
    fi
fi
